apiVersion: v1
kind: Service
metadata:
  name: api-js-service
  labels:
    app.kubernetes.io/name: api-js
    app.kubernetes.io/instance: api-js-2020
    app.kubernetes.io/version: 2020.1.x
    app.kubernetes.io/component: api-backend
    app.kubernetes.io/part-of: baet-ulink
spec:
  type: NodePort
  ports:
    - targetPort: 4042
      port: 4042
      nodePort: 30042
  selector:
    app: ulink-api-js
    component: api-backend
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-js
  labels:
    app: api-js
    app.kubernetes.io/name: api-js
    app.kubernetes.io/instance: api-js-2020
    app.kubernetes.io/version: 2020.1.x
    app.kubernetes.io/component: api-backend
    app.kubernetes.io/part-of: baet-ulink
spec:
  replicas: 1
  #strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxSurge: 1
  #    maxUnavailable: 1
  selector:
    matchLabels:
      app: ulink-api-js
      component: api-backend
    #matchExpressions:
    #  - {key: app, operator: In, values: ['ulink-api-js']}
    #  - {key: type, operator: In, values: ['api-backend']}
    #matchExpressions:
    #  - key: app
    #    operator: in
    #    values: ['ulink-api-js']
  template:
    metadata:
      labels:
        app: ulink-api-js
        component: api-backend
    spec:
      #serviceAccountName: catpet
      #restartPolicy: Never
      #securityContext:
      #  runAsNonRoot: true
      containers:
        - name: ulink-api-js
          image: zeusbaba/ulink-api-js:2020.1.20
          imagePullPolicy: Always
          #securityContext:
          #  runAsUser: 1000
          #  capabilities:
          #    add: ["SYS_TIME"]
          #volumeMounts:
          #  - name: api-secrets-ulink
          #    mountPath: /usr/src/app/api-secrets
          #volumeMounts:
          #  - mountPath: /api-data
          #    name: api-data
          #env:
          #  - name: key
          #    value: val
          envFrom:
            - secretRef:
                name: api-secrets-ulink
            #- configMapRef:
            #    name: baet-configmap
          resources:
            requests:
              memory: "96Mi"
              #cpu: 0.5
            limits:
              memory: "128Mi"
              #cpu: 0.5
          ports:
            - name: app-port
              containerPort: 4042
              #hostPort: 4042
        # Protect slow starting containers with startup probes
#          startupProbe:
#            httpGet:
#              path: /k8s-status
#              port: app-port
          # 3 * 10 = 30secs
#            failureThreshold: 3
#            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /k8s-status
              port: app-port
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /k8s-status
              port: app-port
            initialDelaySeconds: 10
            periodSeconds: 300
            timeoutSeconds: 10
            failureThreshold: 4
          # Protect slow starting containers with startup probes
          startupProbe:
            httpGet:
              path: /k8s-status
              port: app-port
            # 30 * 10 = 300secs
            failureThreshold: 20
            periodSeconds: 1
      #volumes:
      #  - name: ulink-api-secrets
      #    secret:
      #      secretName: ulink-api-secrets
      #volumes:
      #  - name: ulink-api-data
      #    hostPath:
      #      path: /ulink-api-data
      #      type: Directory
